#!/bin/bash
# Install Apache Web Server
yum install -y httpd
# Download web site files
wget https://raw.githubusercontent.com/ashapoaws/ec2/master/index.html 
cp index.html /var/www/html/ 
# Turn on web server 
chkconfig httpd on 
service httpd start
